name: CI

on:
  push:
    branches:
      - dev
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  node-package-ci:
    uses: cyaris/shared-automation/.github/workflows/ci.yml@main
    with:
      local-dependency-repositories: |
        cyaris/svelte-lib:svelte-lib:${{ github.ref_name == 'dev' && 'dev' || 'main' }}
        cyaris/fireworks:fireworks:${{ github.ref_name == 'dev' && 'dev' || 'main' }}
      run-test: true
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
