name: Release Please

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-manual-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate manual dispatcher
        if: ${{ github.event_name == 'workflow_dispatch' && github.actor != 'cyaris' }}
        run: |
          printf "Manual dispatch is restricted to cyaris.\n" >&2
          exit 1

  release-please:
    needs: validate-manual-dispatch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
