name: Rollup

on:
  push:
    branches:
      - dev
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Print the S3 operations without writing objects.
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  rollup:
    permissions:
      contents: read
      id-token: write
    uses: cyaris/shared-automation/.github/workflows/rollup.yml@main
    with:
      additional-ci-local-dependency-repositories: |
        cyaris/fireworks:fireworks:main
      bundle-files: |
        bundle.css:text/css
        bundle.js:application/javascript
      s3-bucket: cyaris.github.io
      s3-prefix: mastermind
      aws-region: us-east-2
      aws-role-to-assume: ${{ vars.AWS_ROLLUP_UPLOAD_ROLE_ARN }}
      manual-dry-run: ${{ inputs.dry-run || false }}
      rollup-local-dependency-repositories: |
        cyaris/fireworks:fireworks:main
    secrets:
      CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
